### ISSUE TITLE
Make `queue` less specific

### ISSUE THREAD

**Issue by uppfinnarn** [halonsecurity/halonctl#20]
We have a whole pile of data we could get out of there, why limit it to only `mail-queue-count`?

**Comment by eriklax** [comment]
A ```-l``` flag will be added to ```statd```in 3.3r2 listing all available counters

```
system-cpu-usage
system-cpu-temperature
system-mem-usage
...
```

**Comment by eriklax** [comment]
module fixed in https://github.com/halonsecurity/halonctl/commit/4fcec243fc8b7cd4f4ea94fdf56aeca245f13fe6
-l got fixed in https://github.com/halonsecurity/halonctl/commit/fdfcc59bf18cf3837bf7cde1312214ce0551a2e7
